### ISSUE TITLE
Adding readme.md

### ISSUE THREAD

**Issue by rangira** [syncopika/threejs-projects#6]
Hi 

Could we please add a readme file to run the project and contribute to the project.

**Comment by syncopika** [comment]
@rangira

hi and thanks very much for this request! I can certainly add to the readme how to run the project :)

as for contributions, I think I would like to continue cleaning up my code first on my own before accepting PRs. I'll make a note in the readme.

**Comment by syncopika** [comment]
and done! feel free to reopen this issue and let me know if anything is still unclear. thank you!
